defmodule DobbyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dobby

  @doc false
  # Phoenix 1.8 disallows `check_origin: false` and `check_csrf: false` together on longpoll.
  # Session+query CSRF for the first GET often fails behind proxies (cookie/session timing),
  # causing `connect` to return :error → HTTP 403. A permissive MFA satisfies the transport
  # rule without the brittle longpoll CSRF path; websocket still uses its own options.
  def live_longpoll_origin?(_uri), do: true

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dobby_key",
    signing_salt: "2ddDKILk",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      # Some in-app WebViews (e.g. custom mobile containers) may omit/alter
      # Origin behavior and get blocked before session/csrf validation.
      check_origin: false,
      connect_info: [:peer_data, :user_agent, session: @session_options]
    ],
    # Must stay enabled when assets use LiveSocket longPollFallbackMs: WebSocket-only
    # stacks break LiveView behind proxies/WAF that block upgrades; longpoll shares
    # the same Origin/session strategy as websocket above.
    longpoll: [
      check_origin: {__MODULE__, :live_longpoll_origin?, []},
      check_csrf: false,
      connect_info: [:peer_data, :user_agent, session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dobby,
    gzip: not code_reloading?,
    only: DobbyWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dobby
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DobbyWeb.Router
end
