defmodule DobbyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dobby

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dobby_key",
    signing_salt: "2ddDKILk",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      # Some in-app WebViews (e.g. custom mobile containers) may omit/alter
      # Origin behavior and get blocked before session/csrf validation.
      check_origin: false,
      connect_info: [:peer_data, :user_agent, session: @session_options]
    ],
    # Must stay enabled when assets use LiveSocket longPollFallbackMs: WebSocket-only
    # stacks break LiveView behind proxies/WAF that block upgrades; longpoll shares
    # the same Origin/session strategy as websocket above.
    longpoll: [
      # Behind Nginx, conn.port is the upstream (e.g. 4000) while the browser Origin uses the
      # public port (80). check_origin: :conn then rejects the request with 403. Keep origin
      # checks off here like websocket; Phoenix 1.8+ still requires either non-false check_origin
      # or check_csrf — use session-backed CSRF (query _csrf_token + _dobby_key cookie).
      check_origin: false,
      check_csrf: true,
      connect_info: [:peer_data, :user_agent, session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dobby,
    gzip: not code_reloading?,
    only: DobbyWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dobby
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DobbyWeb.Router
end
